--- 

baseurl:        "http://manalas.com/"
languageCode:   "en-us"
title:          "Manalas"

params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "ELAO"

menu:
  main:
      - Name:       "About"
        Identifier: "about"
        URL:        "/about"
        Weight:     80
      - Name:       "Recipes"
        Identifier: "recipes"
        URL:        "/recipes"
        Weight:     90
      - Name:       "Blog"
        Identifier: "blog"
        URL:        "/blog"
        Weight:     100
      - Name:       "Contributors"
        Identifier: "contributors"
        URL:        "/contributors"
        Weight:     110
  sidebar:
      - Name:       "Mon lien 1"
        Identifier: "mon-lien-1"
        URL:        "/about/mon-lien-1"
      - Name:       "Mon lien 2"
        Identifier: "mon-lien-2"
        URL:        "/about/mon-lien-2"
      - Name:       "Mon lien 3"
        Identifier: "mon-lien-3"
        URL:        "/about/mon-lien-3"
